"""Nicokara (ニコカラ) 格式导出器。

Nicokara 格式用于ニコカラメーカー工具。
特点：
- 特定的时间格式
- 支持逐字时间标签
- 支持颜色标记
"""

from typing import List, Dict
from .base import BaseExporter, ExportError
from strange_uta_game.backend.domain import Project, LyricLine, Singer


class NicokaraExporter(BaseExporter):
    """Nicokara 格式导出器

    导出适用于ニコカラメーカー的歌词格式。
    """

    @property
    def name(self) -> str:
        return "Nicokara"

    @property
    def description(self) -> str:
        return "ニコカラメーカー用格式"

    @property
    def file_extension(self) -> str:
        return ".txt"

    @property
    def file_filter(self) -> str:
        return "Nicokara 歌词文件 (*.txt)"

    def export(self, project: Project, file_path: str) -> None:
        """导出为 Nicokara 格式"""
        self._validate_project(project)

        lines = []

        # 文件头
        lines.append("# Nicokara Lyrics Format")
        lines.append(f"# Generated by StrangeUtaGame")

        if project.metadata:
            if project.metadata.title:
                lines.append(f"# Title: {project.metadata.title}")
            if project.metadata.artist:
                lines.append(f"# Artist: {project.metadata.artist}")

        lines.append("")

        # 演唱者定义
        singer_colors = self._generate_singer_colors(project)
        lines.append("# Singers:")
        for singer in project.singers:
            color = singer_colors.get(singer.id, "FFFFFF")
            lines.append(f"# [{singer.name}] #{color}")

        lines.append("")

        # 导出行
        for line in project.lines:
            line_text = self._export_line(line, singer_colors)
            if line_text:
                lines.append(line_text)

        # 写入文件
        try:
            with open(file_path, "w", encoding="utf-8") as f:
                f.write("\n".join(lines))
        except Exception as e:
            raise ExportError(f"写入文件失败: {e}")

    def _generate_singer_colors(self, project: Project) -> Dict[str, str]:
        """生成演唱者颜色映射"""
        colors = {}

        for singer in project.singers:
            # 移除 # 前缀
            color = singer.color.lstrip("#")
            colors[singer.id] = color

        return colors

    def _export_line(self, line: LyricLine, singer_colors: Dict[str, str]) -> str:
        """导出一行歌词"""
        if not line.timetags:
            return f"[00:00.00] {line.text}"

        # 获取演唱者颜色
        singer_color = singer_colors.get(line.singer_id, "FFFFFF")

        # 按时间排序的时间标签
        sorted_tags = sorted(line.timetags, key=lambda t: t.timestamp_ms)

        # 行起始时间
        first_time = sorted_tags[0].timestamp_ms
        time_str = self._format_timestamp(first_time, "nicokara")

        # 如果有多个时间标签，使用逐字格式
        if len(sorted_tags) > 1 and line.chars:
            # 逐字格式: [time]{\k<duration>}char{\k<duration>}char...
            result = [f"[{time_str}]"]

            # 添加颜色标记
            result.append(f"{{\\c&H{singer_color}&}}")

            for i, tag in enumerate(sorted_tags):
                char_idx = min(tag.char_idx, len(line.chars) - 1)
                char = line.chars[char_idx]

                # 计算持续时间
                if i + 1 < len(sorted_tags):
                    duration_ms = sorted_tags[i + 1].timestamp_ms - tag.timestamp_ms
                else:
                    duration_ms = 300

                duration_cs = max(1, duration_ms // 10)
                result.append(f"{{\\k{duration_cs}}}{char}")

            # 重置颜色
            result.append("{\\r}")

            return "".join(result)
        else:
            # 单行格式
            return f"[{time_str}] {line.text}"


class NicokaraWithRubyExporter(NicokaraExporter):
    """带注音的 Nicokara 格式导出器"""

    @property
    def name(self) -> str:
        return "Nicokara (带注音)"

    @property
    def description(self) -> str:
        return "ニコカラメーカー用格式（包含注音信息）"

    def _export_line(self, line: LyricLine, singer_colors: Dict[str, str]) -> str:
        """导出一行歌词（带注音）"""
        base_text = super()._export_line(line, singer_colors)

        # 如果有注音，在注释中添加注音信息
        if line.rubies:
            ruby_info = []
            for ruby in line.rubies[:3]:  # 最多显示 3 个
                ruby_info.append(f"{ruby.text}")

            if ruby_info:
                return f"{base_text}  # 注音: {', '.join(ruby_info)}"

        return base_text
